version: '3.8'
services:
  app:
    image: ${DOCKER_HUB_USERNAME}/${IMAGE_NAME}:${RUN_NUMBER}
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - .env.production
  db:
    image: postgres:16.2
    ports:
      - '5432:5432'
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
