name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-containers:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrest.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Create env file
        run: echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env.production
      - name: Build and push
        uses: docker/build-and-push@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}/:${{ github.run_number }}
      - name: Deploy
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.HOSTNAME }} '
          cd /home/ubuntu/hrm-app/ &&
          git checkout main &&
          git reset --hard origin/main &&
          git pull origin main &&
          docker-compose up -d
          '
